spring.application.name=price-tracker

spring.data.mongodb.database=price_tracker
spring.data.mongodb.uri=mongodb://localhost:27017/price_tracker
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
